version: '2'

services:
    ldap:
        container_name: ldap
        # use the image tag to pull directly from the repo
        # image: rroemhild/test-openldap
        environment:
            LDAP_DOMAIN: "planetexpress.com"
            LDAP_BASEDN: "dc=planetexpress,dc=com"
            LDAP_ORGANISATION: "Planet Express, Inc."
            LDAP_BINDDN: "cn=admin,dc=planetexpress,dc=com"
        # use build tag to use the local repo
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - '10389:389'
            - '10636:10636'
        volumes:
            - data_volume:/var/lib/ldap/
    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "ldap"
            PHPLDAPADMIN_HTTPS: "false"
        ports:
            - "8080:80"
        depends_on:
            - ldap

volumes:
   data_volume:
